enum ActionTypes {
  INCREASE_A = 'INCREASE_A',
  DECREASE_B = 'DECREASE_B',
  UPDATE_A = 'UPDATE_A',
  UPDATE_B = 'UPDATE_B',
  UPDATE_RENTER = 'UPDATE_RENTER',
  UPDATE_USERNAME = 'UPDATE_USERNAME',
  UPDATE_PASSWORD = 'UPDATE_PASSWORD',
  UPDATE_LOGIN_REDIRECT_TO = 'UPDATE_LOGIN_REDIRECT_TO',
  UPDATE_LEASE_AGREEMENT_LINK = 'UPDATE_LEASE_AGREEMENT_LINK',
  UPDATE_LEASE_AGREEMENT_REDIRECT_TO = 'UPDATE_LEASE_AGREEMENT_REDIRECT_TO',
  UPDATE_PAYMENT_REDIRECT_TO = 'UPDATE_PAYMENT_REDIRECT_TO',
  UPDATE_PAYMENT_HISTORY = 'UPDATE_PAYMENT_HISTORY',
}

export default ActionTypes;
